
import zmq
from Heron.communication.socket_for_serialization import Socket

DATA_FORWARDER_SUBMIT_PORT = '5560'
DATA_FORWARDER_PUBLISH_PORT = '5561'
DATA_FORWARDER_CAPTURE_PORT = '5562'

STATE_FORWARDER_SUBMIT_PORT = '5563'
STATE_FORWARDER_PUBLISH_PORT = '5564'
STATE_FORWARDER_CAPTURE_PORT = '5565'

HEARTBEAT_FORWARDER_SUBMIT_PORT = '5566'
HEARTBEAT_FORWARDER_PUBLISH_PORT = '5567'
HEARTBEAT_FORWARDER_CAPTURE_PORT = '5568'

HEARTBEAT_RATE = 5  # in seconds

MAXIMUM_RESERVED_SOCKETS_PER_NODE = 20
