
import zmq
from Heron.communication.socket_for_serialization import Socket

DATA_FORWARDER_SUBMIT_PORT = '5560'
DATA_FORWARDER_PUBLISH_PORT = '5561'
DATA_FORWARDER_CAPTURE_PORT = '5562'

STATE_FORWARDER_SUBMIT_PORT = '5563'
STATE_FORWARDER_PUBLISH_PORT = '5564'
STATE_FORWARDER_CAPTURE_PORT = '5565'

HEARTBEAT_FORWARDER_SUBMIT_PORT = '5566'
HEARTBEAT_FORWARDER_PUBLISH_PORT = '5567'
HEARTBEAT_FORWARDER_CAPTURE_PORT = '5568'

PROOF_OF_LIFE_FORWARDER_SUBMIT_PORT = '5569'
PROOF_OF_LIFE_FORWARDER_PUBLISH_PORT = '5570'
PROOF_OF_LIFE_FORWARDER_CAPTURE_PORT = '5571'

HEARTBEAT_RATE = 1  # in seconds
HEARTBEATS_TO_DEATH = 5

MAXIMUM_RESERVED_SOCKETS_PER_NODE = 20
